import { useState, useEffect } from 'react'
import { Music2, RefreshCw, Download, CheckCircle, ExternalLink, Sparkles, List } from 'lucide-react'

interface ImportResult {
  status: string
  playlist_name: string
  total_tracks: number
  in_library: number
  missing: number
  message: string
}

interface SpotifyPreview {
  playlist: { name: string; track_count: number }
  tracks: Array<{ artist: string; title: string; album: string; in_library: boolean }>
  in_library: number
  missing: number
}

interface LBPlaylist {
  title: string
  mbid: string
  date: string
  creator: string
}

type LBPlaylistType = 'weekly-jams' | 'weekly-exploration'

export default function ImportsPage() {
  // ListenBrainz state
  const [lbPlaylists, setLbPlaylists]   = useState<LBPlaylist[]>([])
  const [lbLoading, setLbLoading]       = useState(false)
  const [lbSelected, setLbSelected]     = useState<LBPlaylistType>('weekly-jams')
  const [lbImporting, setLbImporting]   = useState(false)
  const [lbResult, setLbResult]         = useState<ImportResult | null>(null)
  const [lbError, setLbError]           = useState<string | null>(null)

  // Spotify state
  const [spotifyUrl, setSpotifyUrl]         = useState('')
  const [spotifyFormat, setSpotifyFormat]   = useState<'mp3' | 'flac'>('mp3')
  const [spotifyDownload, setSpotifyDownload] = useState(true)
  const [spotifyLoading, setSpotifyLoading] = useState(false)
  const [spotifyPreview, setSpotifyPreview] = useState<SpotifyPreview | null>(null)
  const [spotifyResult, setSpotifyResult]   = useState<ImportResult | null>(null)
  const [spotifyError, setSpotifyError]     = useState<string | null>(null)
  const [previewing, setPreviewing]         = useState(false)

  // Load available LB playlists
  useEffect(() => {
    const load = async () => {
      setLbLoading(true)
      try {
        const res = await fetch('/api/imports/listenbrainz/playlists')
        if (res.ok) {
          const data = await res.json()
          setLbPlaylists(data.playlists || [])
        }
      } catch {}
      finally { setLbLoading(false) }
    }
    load()
  }, [])

  const importLB = async () => {
    setLbImporting(true)
    setLbResult(null)
    setLbError(null)
    try {
      const res = await fetch(`/api/imports/listenbrainz/${lbSelected}`, { method: 'POST' })
      const data = await res.json()
      if (!res.ok) throw new Error(data.detail || `HTTP ${res.status}`)
      setLbResult(data)
    } catch (e: any) {
      setLbError(e.message)
    } finally {
      setLbImporting(false)
    }
  }

  const previewSpotify = async () => {
    if (!spotifyUrl.trim()) return
    setPreviewing(true)
    setSpotifyPreview(null)
    setSpotifyError(null)
    try {
      const res = await fetch(`/api/imports/spotify/playlist/preview?url=${encodeURIComponent(spotifyUrl)}`)
      const data = await res.json()
      if (!res.ok) throw new Error(data.detail || `HTTP ${res.status}`)
      setSpotifyPreview(data)
    } catch (e: any) {
      setSpotifyError(e.message)
    } finally {
      setPreviewing(false) }
  }

  const importSpotify = async () => {
    if (!spotifyUrl.trim()) return
    setSpotifyLoading(true)
    setSpotifyResult(null)
    setSpotifyError(null)
    try {
      const res = await fetch('/api/imports/spotify/playlist', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ url: spotifyUrl, format_pref: spotifyFormat, download_missing: spotifyDownload }),
      })
      const data = await res.json()
      if (!res.ok) throw new Error(data.detail || `HTTP ${res.status}`)
      setSpotifyResult(data)
      setSpotifyPreview(null)
    } catch (e: any) {
      setSpotifyError(e.message)
    } finally {
      setSpotifyLoading(false)
    }
  }

  return (
    <div className="p-6 max-w-3xl mx-auto space-y-6">
      <h1 className="text-2xl font-bold text-gray-100">Import Playlists</h1>

      {/* ── ListenBrainz ──────────────────────────────────────────────────── */}
      <div className="card space-y-4">
        <div className="flex items-center gap-2">
          <Sparkles className="text-honey-400" size={18} />
          <div>
            <h2 className="font-semibold text-gray-200">ListenBrainz Playlists</h2>
            <p className="text-xs text-gray-500 mt-0.5">
              Import personalised playlists generated by ListenBrainz based on your listening history.
              Requires following <a href="https://listenbrainz.org/user/troi-bot/" target="_blank" rel="noreferrer"
                className="text-honey-400 hover:underline">troi-bot</a> on ListenBrainz.
            </p>
          </div>
        </div>

        {/* Available playlists from LB */}
        {lbPlaylists.length > 0 && (
          <div className="bg-gray-800/50 rounded-lg p-3 space-y-1">
            <div className="text-xs text-gray-500 mb-2 flex items-center gap-1">
              <List size={12} />Available on your ListenBrainz account:
            </div>
            {lbPlaylists.map((pl, i) => (
              <div key={i} className="text-xs text-gray-300 flex items-center gap-2">
                <span className="w-1.5 h-1.5 rounded-full bg-green-500 shrink-0" />
                <span>{pl.title}</span>
                {pl.date && <span className="text-gray-600">{pl.date.slice(0, 10)}</span>}
              </div>
            ))}
          </div>
        )}

        {lbResult ? (
          <div className="bg-green-900/20 border border-green-800 rounded-lg p-4 space-y-2">
            <div className="flex items-center gap-2 text-green-400 font-medium">
              <CheckCircle size={16} />{lbResult.playlist_name}
            </div>
            <p className="text-sm text-gray-300">{lbResult.message}</p>
            <div className="flex gap-4 text-xs text-gray-400">
              <span>Total: {lbResult.total_tracks}</span>
              <span className="text-green-400">In library: {lbResult.in_library}</span>
              {lbResult.missing > 0 && <span className="text-honey-400">Missing: {lbResult.missing}</span>}
            </div>
            <button className="btn-secondary text-xs" onClick={() => setLbResult(null)}>Import Again</button>
          </div>
        ) : (
          <>
            {lbError && (
              <div className="bg-red-900/20 border border-red-800 text-red-300 rounded-lg p-3 text-sm">
                {lbError}
              </div>
            )}

            <div className="flex gap-3 items-end">
              <div className="flex-1">
                <label className="label">Playlist Type</label>
                <select className="input" value={lbSelected}
                  onChange={e => setLbSelected(e.target.value as LBPlaylistType)}>
                  <option value="weekly-jams">Weekly Jams (songs you already know)</option>
                  <option value="weekly-exploration">Weekly Exploration (new discoveries)</option>
                </select>
              </div>
              <button className="btn-primary flex items-center gap-2 shrink-0"
                onClick={importLB} disabled={lbImporting}>
                <RefreshCw size={14} className={lbImporting ? 'animate-spin' : ''} />
                {lbImporting ? 'Importing...' : 'Import'}
              </button>
            </div>

            <div className="text-xs text-gray-600 space-y-0.5">
              <p>• <strong className="text-gray-500">Weekly Jams</strong> — songs from your listening history. Creates a playlist from existing library tracks.</p>
              <p>• <strong className="text-gray-500">Weekly Exploration</strong> — new music you haven't heard. Missing tracks will be downloaded.</p>
              <p>• Playlists are generated on Monday mornings. Run on Tuesday for best results.</p>
            </div>
          </>
        )}
      </div>

      {/* ── Spotify ───────────────────────────────────────────────────────── */}
      <div className="card space-y-4">
        <div className="flex items-center gap-2">
          <Music2 className="text-green-400" size={18} />
          <div>
            <h2 className="font-semibold text-gray-200">Spotify Playlist</h2>
            <p className="text-xs text-gray-500 mt-0.5">
              Paste any public Spotify playlist URL. No login or API key required.
              Missing tracks will be downloaded via slskd, then a playlist is created in Jellyfin.
            </p>
          </div>
        </div>

        <div className="space-y-3">
          <div>
            <label className="label">Spotify Playlist URL</label>
            <input className="input" placeholder="https://open.spotify.com/playlist/..."
              value={spotifyUrl}
              onChange={e => { setSpotifyUrl(e.target.value); setSpotifyPreview(null); setSpotifyResult(null) }} />
          </div>

          <div className="grid grid-cols-2 gap-3">
            <div>
              <label className="label">Download Format</label>
              <select className="input" value={spotifyFormat}
                onChange={e => setSpotifyFormat(e.target.value as 'mp3' | 'flac')}>
                <option value="mp3">MP3</option>
                <option value="flac">FLAC</option>
              </select>
            </div>
            <div className="flex items-end pb-0.5">
              <label className="flex items-center gap-2 cursor-pointer">
                <input type="checkbox" checked={spotifyDownload}
                  onChange={e => setSpotifyDownload(e.target.checked)}
                  className="w-4 h-4 accent-honey-500" />
                <span className="text-sm text-gray-300">Download missing tracks</span>
              </label>
            </div>
          </div>

          <div className="flex gap-2">
            <button className="btn-secondary flex items-center gap-1"
              onClick={previewSpotify} disabled={!spotifyUrl.trim() || previewing}>
              <ExternalLink size={13} />{previewing ? 'Loading...' : 'Preview'}
            </button>
            <button className="btn-primary flex items-center gap-2"
              onClick={importSpotify} disabled={!spotifyUrl.trim() || spotifyLoading}>
              <Download size={14} className={spotifyLoading ? 'animate-pulse' : ''} />
              {spotifyLoading ? 'Importing...' : 'Import Playlist'}
            </button>
          </div>
        </div>

        {spotifyError && (
          <div className="bg-red-900/20 border border-red-800 text-red-300 rounded-lg p-3 text-sm">
            {spotifyError}
          </div>
        )}

        {spotifyPreview && (
          <div className="space-y-3">
            <div className="bg-gray-800 rounded-lg p-3">
              <div className="font-medium text-gray-200">{spotifyPreview.playlist.name}</div>
              <div className="flex gap-4 mt-2 text-xs">
                <span className="text-gray-400">{spotifyPreview.playlist.track_count} tracks</span>
                <span className="text-green-400">{spotifyPreview.in_library} in library</span>
                <span className="text-honey-400">{spotifyPreview.missing} missing</span>
              </div>
            </div>
            <div className="space-y-1 max-h-48 overflow-y-auto">
              {spotifyPreview.tracks.map((track, i) => (
                <div key={i} className="flex items-center gap-2 text-xs py-1 border-b border-gray-800">
                  <span className={`w-2 h-2 rounded-full shrink-0 ${track.in_library ? 'bg-green-500' : 'bg-gray-600'}`} />
                  <span className="text-gray-200 truncate">{track.title}</span>
                  <span className="text-gray-500 truncate">{track.artist}</span>
                  {track.in_library && <span className="ml-auto text-green-500 shrink-0">✓</span>}
                </div>
              ))}
            </div>
          </div>
        )}

        {spotifyResult && (
          <div className="bg-green-900/20 border border-green-800 rounded-lg p-4 space-y-2">
            <div className="flex items-center gap-2 text-green-400 font-medium">
              <CheckCircle size={16} />{spotifyResult.playlist_name}
            </div>
            <p className="text-sm text-gray-300">{spotifyResult.message}</p>
            <p className="text-xs text-gray-500">Playlist will appear in Jellyfin and Symfonium when ready.</p>
          </div>
        )}
      </div>
    </div>
  )
}
